apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  annotations:
    azure.workload.identity/client-id: "242f2887-a31c-43ff-a162-ee21c34a91fa"

---
apiVersion: v1
kind: Pod
metadata:
  name: my-app-workload-identity-pod
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: vault
  containers:
    - name: c2
      image: docker.io/chaitu1812/az-cli


  AKS_CLUSTER_NAME="dev-eks"
  AKS_RG_NAME="MC_iteration-1_dev-eks_ukwest"

az aks show -n $AKS_CLUSTER_NAME -g $AKS_RG_NAME --query "{oidcIssuerEnabled: oidcIssuerProfile.enabled, workloadIdentityEnabled: workloadIdentityProfile.enabled}"