apiVersion: v1
kind: Pod
metadata:
  name: my-app-workload-identity-pod
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: vault
  containers:
    - name: c2
      image: bitnami/azure-cli:latest
      command: ["sleep","10000s"]
